### PR TITLE
Fix issue #20 (harden/restore instead of enable/disable)

### PR DESCRIPTION
**Pull request by obsti8383**

### CODE REVIEW

**Comment by ccoenen** [comment]
This is a very important start - making the parameter to the function easier to understand. There's another part to #20 though: the tracking of the previous state. If I applied some of these settings manually already (which I find to be very probable, given the current audience for such a tool!) and I hit "restore" then I'll still restore to factory default (which is worse than what I started with). I personally would wish for "restore to the previous state" instead of "factory default".

**Comment by ccoenen** [comment]
This would involve keeping a list of all changes that were applied, so it's probably going to be a very large change. I'd be in favor of merging this change and keeping #20 open until the other problem can be tackle as well.

**Comment by ccoenen** [comment]
("in favor of merging this" means: i find the change important and it looks alright, but I can't verify if it's technically sound and/or complete! This would have to be reviewed by someone closer to the project or someone familiar with the go language.)

**Comment by obsti8383** [comment]
i fully agree. We can keep #20 open. @botherder  can check on the code.

**Comment by botherder** [comment]
Wondful.

**Pull request merged**
