### PR TITLE
Add new ASR rules

### PR DESCRIPTION
**Pull request by obsti8383**

### CODE REVIEW

**Comment by obsti8383** [comment]
I think we have one issue here. When activating all the rules, a freshly compiled hardentools.exe also will be blocked (by the "block executable files from running unless they meet a prevalence, age, or trusted list criterion" 
Perhaps signing will help. To be tested.

**Comment by obsti8383** [comment]
Please don't merge yet due to blocking of hardentools. Either we have to remove that ASR rule or checking if code signing works (working on it)

**Comment by botherder** [comment]
Other than that I don't have a signing certificate anymore, the problem with that is also that we can no longer use Travis' build system for release packaging.

**Comment by obsti8383** [comment]
@botherder removed the problematic ASR rule, looks good now.

**Pull request merged**
