### PR TITLE
Added ActiveX for Office and AutoRun

### PR DESCRIPTION
**Pull request by obsti8383**
still needs some testing, especially Win 7 & 8 (until now only tested for Win 10 64Bit)

### CODE REVIEW

**Comment by botherder** [comment]
I see there are some issues with indentation. Can you please check them and update the pull request? Otherwise looks good. Thanks.

**Comment by obsti8383** [comment]
done.

**Comment by obsti8383** [comment]
Hmm, this is strange. Could it be that your editor is using spaces instead of tabs?

**Comment by botherder** [comment]
Yes, we use 4-spaces tabs, not regular tabs.

**Comment by obsti8383** [comment]
Yeah, no problem. Should work now (also switched from console output to window).

**Comment by botherder** [comment]
Current changes break the proper indentation of license comments at top tho :P

**Comment by obsti8383** [comment]
Should now really be fixed. Sorry.

**Comment by botherder** [comment]
Thank you!

**Pull request merged**
