### PR TITLE
Code Cleanup for further improvements / adds isHardened() methods

### PR DESCRIPTION
**Pull request by obsti8383**
All subjects to harden must now follow the HardenInterface which right now consist of three methods:
- isHardened()  // returns true if subject has already been hardened (false otherwise)
- harden(harden bool)  // harden or restore subject
- name()  // gets a short name of the subject topic 

Expert settings now verify if subject has NOT been hardened in case of "Restore" mode and disables the corresponding checkbox.

GUI is now built dynamically using the information supplied in the HardenInterfaces (name, for now).

After hardening/restore the status of the hardening of each subject is shown in event window.

This needs further improvement:
- Bring back the "long" names / description for each harden subject in the expert settings and the events output. (Additional method and parameter required for the different structs)
- Test if all hardening is still working (rework might have been subject to Copy&Paste errors)
- Redesign event windows or output to fit into the windows (perfect would be to use some icons for each subject (using a red/green status indicator)
- Decide when isHardened() should deliver "true". Only if everything has been hardened (to verify successful hardening) or even if only one thing has been hardened (to be remembered in the registry), to alway allow for a full restore, or both things in different methods?

### CODE REVIEW

**Comment by botherder** [comment]
I feel like this level of rewrite might require creating a separate branch to make sure that it is developed and tested appropriately before being merged in master. Thoughts?

**Comment by obsti8383** [comment]
Good point. I agree 100%. Could you create one?

**Comment by botherder** [comment]
https://github.com/securitywithoutborders/hardentools/tree/refactor

**Comment by obsti8383** [comment]
@botherder : Changed the base of the pull request to refactor

**Pull request merged**
