### PR TITLE
Disable Powershell

### PR DESCRIPTION
**Pull request by obsti8383**
Nex, added the disabling of Powershell.exe via explorer.exe

You can build the exe that requires admin rights via build_admin.sh. The normal exe will also try, but will fail with an error message for the user.

It only works if the user that starts the .exe also has administrative rights himself. If "runas" with an other user is done, of course the other user will get the entries.

Proposal for next steps:
1. Do some more testing
2. Add registry keys to all users, if admin rights are available.

### CODE REVIEW

**Comment by botherder** [comment]
Thanks for this!
Are admin privileges really necessary to create those HKCU keys
If so, could you update your pull request with a few things?
- Make sure the code is up-to-date with recent changes, so that the pull request is merge-able.
- I think it's fine to have one build and require admin privileges for all, instead of having to distribute two builds.

**Comment by obsti8383** [comment]
Yes, admin privileges are necessary. I've merged with recent changes and the standard build now requires admin privileges. You can give it a try.

Since it currently only works for the user that starts the exe, an option would be to use HKLM settings (where available) and iterate over all HKCU entries in the future. That would restrict more advanced user somehow (that might want to use a second user to be able to still start cmd.exe and so on), but would also work for setups where multiple users should be protected or where the standard user has no admin privileges.
What do you think?

**Comment by botherder** [comment]
It seems to be working well. The only note I have, is whether deleting the enter DisallowRun key might be excessive, in the case other pre-existing records unrelated to this tool were present there.

The other question I was asking myself was whether disabling cmd.exe might be excessive or not. I can imagine that for most users that would be ok. However, in the future I guess we might want to have some advanced option to disable some modules, so that more advanced users can decide whether to leave some features/programs untouched.

That will be more of a UI work than anything.

**Comment by botherder** [comment]
@obsti8383 Pinging you here regarding disabling cmd.exe. Any additional thoughts?

**Comment by obsti8383** [comment]
@nex I thought disabling cmd.exe was consequent since it could be used for starting powershell. And normal users rarely need it. However it makes troubleshooting IT problems quite hard. So it depends on your experience regarding actual attacks/malware if we should keep it in or move it to the "advanced" user section for later.
Regarding "DisallowRun": Yes, the whole implementation is a little bit dirty right now, since If something's already there we would overwrite that anyhow with the 1,2,3 values right now. For a 1.0 version i have to fix that by remembering the old setting and append our values after existing ones.

**Comment by obsti8383** [comment]
@botherder Just saw an article in c't from Heise (c't 5/2017, page 144). They analyzed a Office Macro that did just that: cmd.exe /c powershell.exe [...]

**Comment by obsti8383** [comment]
@botherder I did some fixes for the above mentioned problems. If you accept my UAC pull request, i would add that as a second pull afterwards (would be easier for me because i worked on basis of the UAC pull request).

**Pull request merged**
